
project_id = "awraiakbiahrzncoeyya"

[auth]
# Enable cookie-based auth across the whole project
enable_cookies = true

[auth.cookies]
name = "sb-auth-token"
lifetime = 604800 # 1 week in seconds
domain = ""
path = "/"
same_site = "lax"
secure = true
http_only = true

[functions.send-email]
verify_jwt = true

